jobs:
  - name: leofs_deploy
    plan:
    - aggregate:
      - get: leofs_concourse
        trigger: true
      - get: leofs_ansible
        trigger: true
      - get: leofs_src
        trigger: true

    - task: deploy_leofs
      config:
        platform: linux
        image: docker:///windkithk/leofs_deploy
        inputs:
        - name: leofs_concourse
        - name: leofs_ansible
        - name: leofs_src
        run:
          path: leofs_concourse/TestScenario1/files/deploy_leofs.sh
          args:
            - {{ANSIBLE_KEY}}

resources:
  - name: leofs_concourse
    type: git
    source: 
      uri: https://github.com/leo-project/leofs_concourse.git
      branch: master
  - name: leofs_ansible
    type: git
    source: 
      uri: https://github.com/leo-project/leofs_ansible.git
      branch: master
  - name: leofs_src
    type: git
    source:
      uri: https://github.com/leo-project/leofs.git
      branch: master
