resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
  - name: leofs_concourse
    type: git
    source:
      uri: https://github.com/leo-project/leofs_concourse.git
      branch: master
  - name: leofs_ansible
    type: git
    source:
      uri: https://github.com/leo-project/leofs_ansible.git
      branch: master
  - name: leofs_src
    type: git
    source:
      uri: https://github.com/leo-project/leofs.git
      branch: master
  - name: leofs_client_tests
    type: git
    source:
      uri: https://github.com/leo-project/leofs_client_tests.git
      branch: develop
  - name: timer_daily
    type: time
    source: {interval: 24h}
  - name: slack-alert
    type: slack-notification
    source:
      url: {{SLACK_URL}}

jobs:
  - name: leofs_deploy
    plan:
    - aggregate:
      - get: leofs_concourse
      - get: leofs_ansible
      - get: leofs_src
        trigger: true
      - get: timer_daily
        trigger: true
      - get: leofs_client_tests
        trigger: true

    - task: run_ansible
      config:
        platform: linux
        image: docker:///windkithk/leofs_deploy
        inputs:
        - name: leofs_concourse
        - name: leofs_ansible
        - name: leofs_src
        run:
          path: leofs_concourse/S1/files/deploy_leofs.sh
          args:
            - {{ANSIBLE_KEY}}
      on_failure:
        put: slack-alert
        params:
          text: |
            Build LeoFS from Source Failed, check at $ATC_EXTERNAL_URL/builds/$BUILD_ID

  - name: client_test
    plan:
    - aggregate:
      - get: leofs_src
        passed: [leofs_deploy]
        trigger: true
      - get: timer_daily
        passed: [leofs_deploy]
        trigger: true
      - get: leofs_client_tests
        passed: [leofs_deploy]
        trigger: true
      - get: leofs_concourse
#        passed: [leofs_deploy]
    - aggregate:
      - task: aws-sdk-java
        config:
          platform: linux
          image: docker:///windkithk/leofs_tester
          inputs:
          - name: leofs_concourse
          - name: leofs_client_tests
          run:
            path: leofs_concourse/S1/files/run_client_tests.sh
            args: ["aws-sdk-java", {{LEOFS_GW_HOST}},{{LEOFS_GW_PORT}}]
      - task: aws-sdk-php
        config:
          platform: linux
          image: docker:///windkithk/leofs_tester
          inputs:
          - name: leofs_concourse
          - name: leofs_client_tests
          run:
            path: leofs_concourse/S1/files/run_client_tests.sh
            args: ["aws-sdk-php", {{LEOFS_GW_HOST}},{{LEOFS_GW_PORT}}]
      - task: aws-sdk-ruby
        config:
          platform: linux
          image: docker:///windkithk/leofs_tester
          inputs:
          - name: leofs_concourse
          - name: leofs_client_tests
          run:
            path: leofs_concourse/S1/files/run_client_tests.sh
            args: ["aws-sdk-ruby", {{LEOFS_GW_HOST}},{{LEOFS_GW_PORT}}]
      - task: boto
        config:
          platform: linux
          image: docker:///windkithk/leofs_tester
          inputs:
          - name: leofs_concourse
          - name: leofs_client_tests
          run:
            path: leofs_concourse/S1/files/run_client_tests.sh
            args: ["boto", {{LEOFS_GW_HOST}},{{LEOFS_GW_PORT}}]
      - task: erlcloud
        config:
          platform: linux
          image: docker:///windkithk/leofs_tester
          inputs:
          - name: leofs_concourse
          - name: leofs_client_tests
          run:
            path: leofs_concourse/S1/files/run_client_tests.sh
            args: ["erlcloud", {{LEOFS_GW_HOST}},{{LEOFS_GW_PORT}}]
      - task: jclouds
        config:
          platform: linux
          image: docker:///windkithk/leofs_tester
          inputs:
          - name: leofs_concourse
          - name: leofs_client_tests
          run:
            path: leofs_concourse/S1/files/run_client_tests.sh
            args: ["jclouds", {{LEOFS_GW_HOST}},{{LEOFS_GW_PORT}}]
      on_failure:
        put: slack-alert
        params:
          text: |
            Client Test CI Failed, check at $ATC_EXTERNAL_URL/builds/$BUILD_ID
    - put: slack-alert
      params:
        text: |
          Client Test CI Completed, check at $ATC_EXTERNAL_URL/builds/$BUILD_ID
