jobs:
  - name: leofs_basho_bench
    serial: true
    plan:
    - aggregate:
      - get: leofs_concourse
        trigger: true
      - get: leofs_basho_bench_src
        trigger: true

    - task: setup_basho_bench
      config:
        platform: linux
        image: docker:///windkithk/leofs_basho_bench
        inputs:
        - name: leofs_concourse
        outputs:
        - name: leofs_basho_bench_conf
        run:
          path: leofs_concourse/files/set_basho_bench_conf.sh
          args: [{{LEOFS_GW_HOST}},{{LEOFS_GW_PORT}}]

    - task: build_basho_bench
      config:
        platform: linux
        image: docker:///windkithk/leofs_basho_bench
        inputs:
        - name: leofs_basho_bench_src
        - name: leofs_concourse
        run:
          path: leofs_concourse/files/build_basho_bench.sh
        outputs:
        - name: leofs_basho_bench_bin
  
    - task: run_basho_bench
      config:
        platform: linux
        image: docker:///windkithk/leofs_basho_bench
        inputs:
        - name: leofs_basho_bench_bin
        - name: leofs_basho_bench_conf
        run:
          path: ./basho_bench 
          args: ["../leofs_basho_bench_conf/test.conf"]
          dir: leofs_basho_bench_bin

#    - task: cat_test_conf
#      config:
#        platform: linux
#        image: docker:///windkithk/leofs_basho_bench
#        inputs:
#        - name: leofs_basho_bench_conf
#        run:
#          path: cat
#          args: ["leofs_basho_bench_conf/test.conf"]
        

resources:
  - name: leofs_concourse
    type: git
    source: 
      uri: https://github.com/leo-project/leofs_concourse.git
      branch: master
  - name: leofs_basho_bench_src
    type: git
    source:
      uri: https://github.com/leo-project/basho_bench.git
      branch: 1.4
