resources:
  - name: leofs_concourse
    type: git
    source:
      uri: https://github.com/leo-project/leofs_concourse.git
      branch: master
  - name: leofs_ansible
    type: git
    source:
      uri: https://github.com/leo-project/leofs_ansible.git
      branch: master
  - name: leofs_src
    type: git
    source:
      uri: https://github.com/leo-project/leofs.git
      branch: master
  - name: leofs_client_tests
    type: git
    source:
      uri: https://github.com/leo-project/leofs_client_tests.git
      branch: develop
  - name: timer_daily
    type: time
    source: {interval: 4h}

jobs:
  - name: leofs_deploy
    plan:
    - aggregate:
      - get: leofs_concourse
      - get: leofs_ansible
      - get: leofs_src
        trigger: true
      - get: timer_daily
        trigger: true
      - get: leofs_client_tests
        trigger: true

    - task: run_ansible
      config:
        platform: linux
        image: docker:///windkithk/leofs_deploy
        inputs:
        - name: leofs_concourse
        - name: leofs_ansible
        - name: leofs_src
        run:
          path: leofs_concourse/files/deploy_leofs.sh
          args:
            - {{ANSIBLE_KEY}}

  - name: client_test
    plan:
    - aggregate:
      - get: leofs_src
        passed: [leofs_deploy]
        trigger: true
      - get: timer_daily
        passed: [leofs_deploy]
        trigger: true
      - get: leofs_client_tests
        passed: [leofs_deploy]
        trigger: true
      - get: leofs_concourse
        passed: [leofs_deploy]
    - task: leofs_client_tests
      config:
        platform: linux
        image: docker:///windkithk/leofs_tester
        inputs:
        - name: leofs_concourse
        - name: leofs_client_tests
        run:
          path: leofs_concourse/files/run_client_tests.sh
          args: [{{LEOFS_GW_HOST}},{{LEOFS_GW_PORT}}]

