jobs:
  - name: leofs_tester
    plan:
    - aggregate:
      - get: leofs_concourse
        trigger: true
      - get: leofs_client_tests
        trigger: true

    - task: run_client_tests
      config:
        platform: linux
        image: docker:///windkithk/leofs_tester
        inputs:
        - name: leofs_concourse
        - name: leofs_client_tests
        run:
          path: leofs_concourse/files/run_client_tests.sh
          args: [{{LEOFS_GW_HOST}},{{LEOFS_GW_PORT}}]

resources:
  - name: leofs_concourse
    type: git
    source: 
      uri: https://github.com/leo-project/leofs_concourse.git
      branch: master
  - name: leofs_client_tests
    type: git
    source:
      uri: https://github.com/leo-project/leofs_client_tests.git
      branch: develop
