---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: windkithk/leofs_basho_bench

inputs:
- name: leofs_concourse
- name: leofs_basho_bench_src

outputs:
- name: leofs_basho_bench_bin

run:
  path: leofs_concourse/scripts/build_basho_bench.sh

