---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: windkithk/leofs_parser

params:
  BASHO_BENCH_TEST_NAME:
  BASHO_BENCH_ERROR_THRES:
  SLACK_URL:
  CHECK_ONLY:

inputs:
- name: leofs_basho_bench_result
- name: leofs_concourse
- name: leofs_notes

outputs:
- name: leofs_notes_update

run:
  path: leofs_concourse/scripts/parse_basho_bench.sh
