---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: windkithk/leofs_deploy

params:
  ANSIBLE_INVENTORY:
  ANSIBLE_USER:
  ANSIBLE_KEY:

inputs:
- name: leofs_concourse
- name: leofs_ansible
- name: leofs_src

run:
  path: leofs_concourse/scripts/reconfig_gw.sh
