---
platform: linux

image_resource:
  type: docker-image
  source:
    repository: windkithk/leofs_tester

params:
  CLIENT_TEST_SDK:
  AWS_SIGN_VER:
  LEOFS_GW_HOST:
  LEOFS_GW_PORT:

inputs:
- name: leofs_concourse
- name: leofs_client_tests

run:
  path: leofs_concourse/scripts/run_client_tests.sh
