---
platform: linux

image: docker:///windkithk/leofs_basho_bench

params:
  BASHO_BENCH_TEST_NAME:
  BASHO_BENCH_LOAD_CONF:
  BASHO_BENCH_TEST_CONF:

inputs:
- name: leofs_concourse
- name: leofs_basho_bench_bin
- name: leofs_basho_bench_conf

run:
  path: leofs_concourse/scripts/run_basho_bench.sh
