resource_types:
- name: slack-notification
  type: docker-image
  source:
    repository: cfcommunity/slack-notification-resource
    tag: latest

resources:
  - name: leofs_concourse
    type: git
    source:
      uri: https://github.com/leo-project/leofs_concourse.git
      branch: develop
  - name: leofs_ansible
    type: git
    source:
      uri: https://github.com/leo-project/leofs_ansible.git
      branch: master
  - name: leofs_src
    type: git
    source:
      uri: https://github.com/leo-project/leofs.git
      branch: develop
  - name: leofs_basho_bench_src
    type: git
    source:
      uri: https://github.com/leo-project/basho_bench.git
      branch: master
  - name: leofs_notes
    type: git
    source:
      uri: git@github.com:windkit/test.git
      branch: master
      private_key: {{ANSIBLE_KEY}}
  - name: timer_daily
    type: time
    source: {interval: 24h}
  - name: slack-alert
    type: slack-notification
    source:
      url: {{SLACK_URL}}

jobs:
  - name: leofs_deploy
    plan:
    - aggregate:
      - get: leofs_concourse
      - get: leofs_ansible
      - get: leofs_src
      - get: timer_daily
        trigger: true
      - get: leofs_basho_bench_src
        trigger: true

    - task: run_ansible
      file: leofs_concourse/tasks/run_ansible.yml
      params: 
        DO_BUILD: true
        SEND_AVS_ARCHIVE: "leofs_src/apps/leo_gateway/test/nfs_dummy_test_avs.tar.gz"
        ANSIBLE_USER: {{ANSIBLE_USER}}
        ANSIBLE_KEY: {{ANSIBLE_KEY}}
        ANSIBLE_INVENTORY: leofs_concourse/ansible/hosts.small.r1.nfs 
        LEOFS_GW_HOST: {{LEOFS_GW_HOST}}

  - name: test_nfs
    plan:
    - aggregate:
      - get: leofs_src
        passed: [leofs_deploy]
      - get: timer_daily
        passed: [leofs_deploy]
        trigger: true
      - get: leofs_concourse
      - get: leofs_basho_bench_src

    - task: nfs_integration
      privileged: true
      file: leofs_concourse/tasks/run_nfs_integration_test.yml
      params:
        LEOFS_GW_HOST: {{LEOFS_GW_HOST}}
        NFS_MOUNT_TOKEN: {{NFS_MOUNT_TOKEN}}

      on_failure:
        put: slack-alert
        params:
          text: |
            NFS Integration Test CI Failed, check at $ATC_EXTERNAL_URL/builds/$BUILD_ID
      on_success:
        put: slack-alert
        params:
          text: |
            NFS Integration Test CI Completed, check at $ATC_EXTERNAL_URL/builds/$BUILD_ID

  - name: basho_bench_nfs
    plan:
    - aggregate:
      - get: leofs_src
        passed: [test_nfs]
      - get: timer_daily
        passed: [test_nfs]
        trigger: true
      - get: leofs_basho_bench_src
        passed: [test_nfs]
        trigger: true
      - get: leofs_concourse
      - get: leofs_notes

    - task: setup_basho_bench
      file: leofs_concourse/tasks/setup_basho_bench.yml
      params:
        LEOFS_GW_HOST: {{LEOFS_GW_HOST}}
        LEOFS_GW_PORT: {{LEOFS_GW_PORT}}

    - task: build_basho_bench
      file: leofs_concourse/tasks/build_basho_bench.yml

    - task: basho_bench
      privileged: true
      file: leofs_concourse/tasks/run_basho_bench_nfs.yml
      params:
        LEOFS_GW_HOST: {{LEOFS_GW_HOST}}
        NFS_MOUNT_TOKEN: {{NFS_MOUNT_TOKEN}}
        BASHO_BENCH_TEST_NAME: "lfile_image_f4k"
        BASHO_BENCH_LOAD_CONF: "lfile_image_f4k_load.conf"
        BASHO_BENCH_TEST_CONF: "lfile_image_f4k_r95w5_5min.conf"

    - task: parse_log
      file: leofs_concourse/tasks/parse_basho_bench.yml
      params:
        BASHO_BENCH_TEST_NAME: "lfile_image_f4k"
        BASHO_BENCH_ERROR_THRES: 0.1
        CHECK_ONLY: true

      on_failure:
        put: slack-alert
        params:
          text: |
            NFS Test CI Failed, check at $ATC_EXTERNAL_URL/builds/$BUILD_ID
      on_success:
        put: slack-alert
        params:
          text: |
            NFS Test CI Completed, check at $ATC_EXTERNAL_URL/builds/$BUILD_ID

  - name: reconfig_gateway
    plan:
    - aggregate:
      - get: leofs_src
        passed: [basho_bench_nfs]
      - get: leofs_concourse
      - get: leofs_ansible
      - get: timer_daily
        passed: [basho_bench_nfs]
        trigger: true
      - get: leofs_basho_bench_src
        passed: [basho_bench_nfs]
        trigger: true

    - task: reconfig_gw
      file: leofs_concourse/tasks/reconfig_gw.yml
      params: 
        ANSIBLE_USER: {{ANSIBLE_USER}}
        ANSIBLE_KEY: {{ANSIBLE_KEY}}
        ANSIBLE_INVENTORY: leofs_concourse/ansible/hosts.small.r1.rest

  - name: basho_bench_rest
    plan:
    - aggregate:
      - get: leofs_src
        passed: [reconfig_gateway]
      - get: timer_daily
        passed: [reconfig_gateway]
        trigger: true
      - get: leofs_basho_bench_src
        passed: [reconfig_gateway]
        trigger: true
      - get: leofs_concourse
      - get: leofs_notes

    - task: setup_basho_bench
      file: leofs_concourse/tasks/setup_basho_bench.yml
      params:
        LEOFS_GW_HOST: {{LEOFS_GW_HOST}}
        LEOFS_GW_PORT: {{LEOFS_GW_PORT}}

    - task: build_basho_bench
      file: leofs_concourse/tasks/build_basho_bench.yml

    - task: basho_bench
      privileged: true
      file: leofs_concourse/tasks/run_basho_bench.yml
      params:
        BASHO_BENCH_TEST_NAME: "image_f4k_rest"
        BASHO_BENCH_LOAD_CONF: "image_f4k_load.conf"
        BASHO_BENCH_TEST_CONF: "image_f4k_r95w5_5min.conf"

    - task: parse_log
      file: leofs_concourse/tasks/parse_basho_bench.yml
      params:
        BASHO_BENCH_TEST_NAME: "image_f4k_rest"
        BASHO_BENCH_ERROR_THRES: 0.1
        CHECK_ONLY: true

      on_failure:
        put: slack-alert
        params:
          text: |
            REST Test CI Failed, check at $ATC_EXTERNAL_URL/builds/$BUILD_ID
      on_success:
        put: slack-alert
        params:
          text: |
            REST Test CI Completed, check at $ATC_EXTERNAL_URL/builds/$BUILD_ID
