resources:
  - name: leofs_concourse
    type: git
    source:
      uri: https://github.com/leo-project/leofs_concourse.git
      branch: develop
  - name: leofs_ansible
    type: git
    source:
      uri: https://github.com/leo-project/leofs_ansible.git
      branch: master
  - name: leofs_src
    type: git
    source:
      uri: https://github.com/leo-project/leofs.git
      branch: develop
  - name: leofs_basho_bench_src
    type: git
    source:
      uri: https://github.com/leo-project/basho_bench.git
      branch: 1.4
  - name: periodic
    type: time
    source: {interval: 72h}

jobs:
  - name: leofs_deploy
    plan:
    - aggregate:
      - get: leofs_concourse
      - get: leofs_ansible
      - get: leofs_src
      - get: periodic
        trigger: true
      - get: leofs_basho_bench_src
        trigger: true

    - task: run_ansible
      file: leofs_concourse/tasks/run_ansible.yml
      params: 
        DO_BUILD: true
        ANSIBLE_USER: {{ANSIBLE_USER}}
        ANSIBLE_KEY: {{ANSIBLE_KEY}}
        ANSIBLE_INVENTORY: leofs_concourse/ansible/hosts.small.rest 
        LEOFS_GW_HOST: {{LEOFS_GW_HOST}}

  - name: basho_bench_rest
    plan:
    - aggregate:
      - get: leofs_src
        passed: [leofs_deploy]
      - get: periodic
        passed: [leofs_deploy]
        trigger: true
      - get: leofs_basho_bench_src
        passed: [leofs_deploy]
        trigger: true
      - get: leofs_concourse

    - task: setup_basho_bench
      file: leofs_concourse/tasks/setup_basho_bench.yml
      params:
        LEOFS_GW_HOST: {{LEOFS_GW_HOST}}
        LEOFS_GW_PORT: {{LEOFS_GW_PORT}}

    - task: build_basho_bench
      file: leofs_concourse/tasks/build_basho_bench.yml
  
    - task: rest
      file: leofs_concourse/tasks/run_basho_bench.yml
      params:
        BASHO_BENCH_TEST_NAME: "image_f4k"
        BASHO_BENCH_LOAD_CONF: "image_f4k_load.conf"
        BASHO_BENCH_TEST_CONF: "image_f4k_r95w5_5min.conf"

    - task: parse_log
      file: leofs_concourse/tasks/parse_basho_bench.yml
      params:
        BASHO_BENCH_TEST_NAME: "image_f4k"
        BASHO_BENCH_ERROR_THRES: 0.1
        SLACK_URL: {{SLACK_URL}}
        CHECK_ONLY: true
