resources:
  - name: leofs_concourse
    type: git
    source:
      uri: https://github.com/leo-project/leofs_concourse.git
      branch: master
  - name: leofs_ansible
    type: git
    source:
      uri: https://github.com/leo-project/leofs_ansible.git
      branch: master
  - name: leofs_src
    type: git
    source:
      uri: https://github.com/leo-project/leofs.git
      branch: master
  - name: leofs_basho_bench_src
    type: git
    source:
      uri: https://github.com/leo-project/basho_bench.git
      branch: 1.4
  - name: leofs_notes
    type: git
    source:
      uri: git@github.com:windkit/test.git
      branch: master
      private_key: {{ANSIBLE_KEY}}
  - name: timer_daily
    type: time
    source: {interval: 24h}

jobs:
  - name: leofs_deploy
    plan:
    - aggregate:
      - get: leofs_concourse
      - get: leofs_ansible
      - get: leofs_src
        trigger: true
      - get: timer_daily
        trigger: true
      - get: leofs_basho_bench_src
        trigger: true

    - task: run_ansible
      file: leofs_concourse/tasks/run_ansible.yml
      params: 
        ANSIBLE_KEY: {{ANSIBLE_KEY}}
        ANSIBLE_INVENTORY: leofs_concourse/ansible/hosts.small 
        LEOFS_GW_HOST: {{LEOFS_GW_HOST}}

  - name: basho_bench
    plan:
    - aggregate:
      - get: leofs_src
        passed: [leofs_deploy]
        trigger: true
      - get: timer_daily
        passed: [leofs_deploy]
        trigger: true
      - get: leofs_basho_bench_src
        passed: [leofs_deploy]
        trigger: true
      - get: leofs_concourse
      - get: leofs_notes

    - task: setup_basho_bench
      file: leofs_concourse/tasks/setup_basho_bench.yml
      params:
        LEOFS_GW_HOST: {{LEOFS_GW_HOST}}
        LEOFS_GW_PORT: {{LEOFS_GW_PORT}}

    - task: build_basho_bench
      file: leofs_concourse/tasks/build_basho_bench.yml
  
    - task: image_f4m
      file: leofs_concourse/tasks/run_basho_bench.yml
      params:
        BASHO_BENCH_TEST_NAME: "image_f4m"
        BASHO_BENCH_LOAD_CONF: "image_f4m_load.conf"
        BASHO_BENCH_TEST_CONF: "image_f4m_r95w5_60min.conf"

    - task: parse_log
      file: leofs_concourse/tasks/parse_basho_bench.yml
      params:
        BASHO_BENCH_TEST_NAME: "image_f4m"
        BASHO_BENCH_ERROR_THRES: 0.1

    - put: leofs_notes
      params: {repository: leofs_notes_update}

